module.exports = [
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 1,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 3,
		liked: true,
		resource_id: 1,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 1,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 1,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 1,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 2,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 3,
		liked: true,
		resource_id: 2,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 2,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 2,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 2,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 3,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 3,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 3,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 3,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 3,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 4,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 4,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 4,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 4,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 4,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 5,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 5,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 5,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 5,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 5,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 6,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 6,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 6,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 6,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 6,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 7,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 7,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 7,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 7,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 7,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 8,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 8,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 8,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 8,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 8,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 9,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 9,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 9,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 9,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 9,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 10,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 10,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 10,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 10,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 10,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 11,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 11,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 11,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 11,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 11,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 12,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 12,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 12,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 12,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 12,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 13,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 13,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 13,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 13,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 13,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 14,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 14,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 14,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 14,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 14,
		user_id: 5,
	},
	{
		comment: 'Profit-focused upward-trending throughput',
		rating: 4,
		liked: true,
		resource_id: 15,
		user_id: 1,
	},
	{
		comment: 'Vision-oriented demand-driven installation',
		rating: 2,
		liked: true,
		resource_id: 15,
		user_id: 2,
	},
	{
		comment: 'Mandatory secondary leverage',
		rating: 1,
		liked: true,
		resource_id: 15,
		user_id: 3,
	},
	{
		comment: '  Configurable zero administration pricing structure',
		rating: 4,
		liked: true,
		resource_id: 15,
		user_id: 4,
	},
	{
		comment: 'Multi-layered zero administration customer loyalty',
		rating: 4,
		liked: true,
		resource_id: 15,
		user_id: 5,
	},
];
