module.exports: [
    {
        resource_id: 1,
        url: 'https://www.google.com',
        title: 'Google search',
        description: 'PURE EVIL',
        favicon: 'https://fillmurray.com/200/300',
        user_id: 1,
    },
    {
        resource_id: 2,
        url: 'https://www.bing.com',
        title: 'Bing',
        description: 'Total rubbish',
        favicon: 'https://fillmurray.com/g/200/300',
        user_id: 2,
    },
    {
        resource_id: 3,
        url: 'https://www.sporcle.com',
        title: 'sporcle',
        description: 'Trivia',
        favicon: 'https://www.fillmurray.com/284/196',
        user_id: 3,
    },
    {
        resource_id: 4,
        url: 'https://www.bbc.co.uk/sport',
        title: 'BBC Sport',
        description: 'Sports updates',
        favicon: 'https://www.fillmurray.com/140/100',
        user_id: 5,
    },
    {
        resource_id: 5,
        url: 'https://www.example.com',
        title: 'Example',
        description: 'Example',
        favicon: 'https://www.fillmurray.com/g/140/100',
        user_id: 4,
    },
]